name: SimpleNameColor
main: SimpleNameColor\SimpleNameColor
author: IanSzot
version: 1.0
api: 3.0.0

description: Easiest way to color player's names using permissions.
website: https://github.com/IanSzot/SimpleNameColor-PMMP

permissions:
  snc:
    description: Main permission
    default: false
    children:
      snc.aqua:
        default: false
      snc.black:
        default: false
      snc.blue:
        default: false
      snc.bold:
        default: false
      snc.darkaqua:
        default: false
      snc.darkblue:
        default: false
      snc.darkgray:
        default: false
      snc.darkgreen:
        default: false
      snc.darkpurple:
        default: false
      snc.darkred:
        default: false
      snc.gold:
        default: false
      snc.gray:
        default: false
      snc.green:
        default: false
      snc.italic:
        default: false
      snc.lightpurple:
        default: false
      snc.obfuscated:
        default: false
      snc.red:
        default: false
      snc.strikethrough:
        default: false
      snc.underline:
        default: false
      snc.yellow:
        default: false
      snc.white:
        default: true
