name: SimpleNameColor
main: IanSzot\SimpleNameColor\SimpleNameColor
author: IanSzot
version: 1.0
api: 3.0.0

description: Easiest way to color player's names using permissions.
website: https://github.com/IanSzot/SimpleNameColor-PMMP

permissions:
  simplenamecolor:
    description: Main permission
    default: false
    children:
      simplenamecolor.aqua:
        default: false
      simplenamecolor.black:
        default: false
      simplenamecolor.blue:
        default: false
      simplenamecolor.bold:
        default: false
      simplenamecolor.darkaqua:
        default: false
      simplenamecolor.darkblue:
        default: false
      simplenamecolor.darkgray:
        default: false
      simplenamecolor.darkgreen:
        default: false
      simplenamecolor.darkpurple:
        default: false
      simplenamecolor.darkred:
        default: false
      simplenamecolor.gold:
        default: false
      simplenamecolor.gray:
        default: false
      simplenamecolor.green:
        default: false
      simplenamecolor.italic:
        default: false
      simplenamecolor.lightpurple:
        default: false
      simplenamecolor.obfuscated:
        default: false
      simplenamecolor.red:
        default: false
      simplenamecolor.strikethrough:
        default: false
      simplenamecolor.underline:
        default: false
      simplenamecolor.yellow:
        default: false
      simplenamecolor.white:
        default: true
